site_name: WARC Cores

nav:
  - Intro: 'index.md'
  - Getting Started: 'getting-started.md'
  - Cores:
    - HLS: '!include ./cores/hls/mkdocs.yml'
    - Migen: '!include ./cores/migen/mkdocs.yml'
    - Verilog: '!include ./cores/verilog/mkdocs.yml'
  - Generators:
    - HLS: '!include ./generators/hls/mkdocs.yml'
    - Migen: '!include ./generators/migen/mkdocs.yml'
    - Verilog: '!include ./generators/verilog/mkdocs.yml'
  - References: 'references.md'

plugins:
  - monorepo

theme:
  name: null
  custom_dir: theme/material
  language: en
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "layers"
  feature:
    tabs: true

repo_name: 'warc/cores'
repo_url: 'https://github.com/warc/cores'